Repository WeAreRoommies/Roomie-Server, pull requests merged in 2025-01, with the labels that each got.

#10 [Feat] #5 쉐어하우스 정보 조회 api 개발
  .github/workflows/cd-workflow.yml
  .idea/gradle.xml
  .idea/misc.xml
  .idea/uiDesigner.xml
  consumer/Dockerfile
  consumer/src/main/java/server/consumer/processor/RoomApplicationProcessor.java
  consumer/src/main/java/server/consumer/repository/HouseRequestRepository.java
  producer/Dockerfile
  producer/src/main/java/server/producer/common/dto/ApiResponseDto.java
  producer/src/main/java/server/producer/common/dto/enums/ErrorCode.java
  producer/src/main/java/server/producer/common/dto/enums/SuccessCode.java
  producer/src/main/java/server/producer/domain/RoomStatistics.java
  producer/src/main/java/server/producer/domain/controller/HouseController.java
  producer/src/main/java/server/producer/domain/controller/MapController.java
  producer/src/main/java/server/producer/domain/controller/RoomController.java
  producer/src/main/java/server/producer/domain/controller/UserController.java
  producer/src/main/java/server/producer/domain/dto/HouseInfoDto.java
  producer/src/main/java/server/producer/domain/dto/MypageDto.java
  producer/src/main/java/server/producer/domain/dto/RoomDto.java
  producer/src/main/java/server/producer/domain/dto/RoommateDto.java
  producer/src/main/java/server/producer/domain/dto/response/HomeInfoResponseDto.java
  producer/src/main/java/server/producer/domain/dto/response/HouseDetailsResponseDto.java
  producer/src/main/java/server/producer/domain/repository/HouseRepository.java
  producer/src/main/java/server/producer/domain/repository/PinRepository.java
  producer/src/main/java/server/producer/domain/repository/UserRepository.java
  producer/src/main/java/server/producer/domain/service/HouseService.java
  producer/src/main/java/server/producer/domain/service/MapService.java
  producer/src/main/java/server/producer/domain/service/QueueService.java
  producer/src/main/java/server/producer/domain/service/RoomService.java
  producer/src/main/java/server/producer/domain/service/UserService.java
  producer/src/main/java/server/producer/entity/GenderPolicyType.java
  producer/src/main/java/server/producer/entity/GenderType.java
  producer/src/main/java/server/producer/entity/House.java
  producer/src/main/java/server/producer/entity/HousingRequest.java
  producer/src/main/java/server/producer/entity/Pin.java
  producer/src/main/java/server/producer/entity/RecentlyViewedHouse.java
  producer/src/main/java/server/producer/entity/Room.java
  producer/src/main/java/server/producer/entity/Roommate.java
  producer/src/main/java/server/producer/entity/User.java
  producer/src/main/resources/application.yaml
Labels: feature

#8 [Feat] #7 필터 조건에 해당하는 매물 조회 api 개발
  producer/src/main/java/server/producer/common/exception/InvalidRequestException.java
  producer/src/main/java/server/producer/domain/RoomStatistics.java
  producer/src/main/java/server/producer/domain/controller/MapController.java
  producer/src/main/java/server/producer/domain/dto/request/FilterRequestDto.java
  producer/src/main/java/server/producer/domain/dto/response/FilterResponseDto.java
  producer/src/main/java/server/producer/domain/repository/FilterRepository.java
  producer/src/main/java/server/producer/domain/service/MapService.java
  producer/src/main/java/server/producer/domain/service/UserService.java
  producer/src/main/java/server/producer/entity/House.java
  producer/src/main/java/server/producer/entity/Room.java
Labels: feature

#11 [Feat] #5 쉐어하우스 정보 조회 api 개발
  .idea/.name
  .idea/gradle.xml
  .idea/misc.xml
  producer/src/main/java/server/producer/domain/controller/HouseController.java
  producer/src/main/java/server/producer/domain/controller/UserController.java
  producer/src/main/java/server/producer/domain/dto/MyPageDto.java
  producer/src/main/java/server/producer/domain/dto/response/HouseDetailsResponseDto.java
  producer/src/main/java/server/producer/domain/repository/HouseRepository.java
  producer/src/main/java/server/producer/domain/service/HouseService.java
  producer/src/main/java/server/producer/entity/House.java
  producer/src/main/java/server/producer/entity/Room.java
  producer/src/main/java/server/producer/entity/RoomFacilityType.java
  producer/src/main/java/server/producer/entity/Roommate.java
  producer/src/main/java/server/producer/entity/SafetyLivingFacilityType.java
  producer/src/test/java/domain/service/HouseServiceTest.java
Labels: feature

#16 [Feat] #15 마이페이지 조회 api 개발
  producer/src/main/java/server/producer/common/dto/enums/SuccessCode.java
  producer/src/main/java/server/producer/domain/controller/UserController.java
  producer/src/main/java/server/producer/domain/dto/response/MyPageResponseDto.java
  producer/src/main/java/server/producer/domain/service/UserService.java
Labels: feature

#17 [Feat] #14 사용자의 찜 리스트 api 개발
  producer/src/main/java/server/producer/common/dto/enums/SuccessCode.java
  producer/src/main/java/server/producer/domain/controller/HouseController.java
  producer/src/main/java/server/producer/domain/dto/response/PinnedListResponseDto.java
  producer/src/main/java/server/producer/domain/repository/HouseRepository.java
  producer/src/main/java/server/producer/domain/service/HouseService.java
Labels: feature

#19 [Feat] #18 하우스 찜 api 개발
  producer/src/main/java/server/producer/common/dto/enums/SuccessCode.java
  producer/src/main/java/server/producer/domain/controller/HouseController.java
  producer/src/main/java/server/producer/domain/dto/MyPageDto.java
  producer/src/main/java/server/producer/domain/repository/PinRepository.java
  producer/src/main/java/server/producer/domain/service/HouseService.java
Labels: feature

#21 [Feat] #13 쉐어하우스 정보 조회(이미지/방) api 개발
  .idea/gradle.xml
  .idea/misc.xml
  producer/src/main/java/server/producer/common/dto/enums/ErrorCode.java
  producer/src/main/java/server/producer/common/dto/enums/SuccessCode.java
  producer/src/main/java/server/producer/domain/controller/HouseController.java
  producer/src/main/java/server/producer/domain/dto/response/ImageDetailsResponseDto.java
  producer/src/main/java/server/producer/domain/dto/response/RoomDetailsResponseDto.java
  producer/src/main/java/server/producer/domain/repository/HouseRepository.java
  producer/src/main/java/server/producer/domain/service/HouseService.java
Labels: feature

#35 [Fear] #23 서비스 테스트 코드 작성
  common/src/main/java/entity/House.java
  producer/src/main/java/server/producer/domain/dto/response/HouseDetailsResponseDto.java
  producer/src/main/java/server/producer/domain/service/HouseService.java
  producer/src/test/java/domain/service/HouseServiceTest.java
  producer/src/test/java/domain/service/UserServiceTest.java
Labels: test

#36 [Feat] #33 레포지토리 테스트코드 작성
  producer/src/main/java/server/producer/domain/repository/HouseRepository.java
  producer/src/main/java/server/producer/domain/service/HouseService.java
  producer/src/test/java/domain/repository/HouseRepositoryTest.java
  producer/src/test/java/domain/service/HouseServiceTest.java
Labels: test

#41 [Fix] EntityNotFoundException으로 수정
  producer/src/main/java/server/producer/domain/service/HouseService.java
Labels: fix

#44 [Fix] #43 Mysql 연동 수정
  .github/workflows/cd-workflow.yml
  common/src/main/java/entity/House.java
  common/src/main/java/entity/Room.java
  common/src/main/java/entity/Roommate.java
  consumer/build.gradle
  consumer/src/main/resources/application.yaml
  consumer/src/test/java/processor/TourQueueProcessorTest.java
  producer/build.gradle
  producer/src/main/java/server/producer/common/dto/enums/SuccessCode.java
  producer/src/main/java/server/producer/domain/repository/FilterRepository.java
  producer/src/main/java/server/producer/domain/service/HouseService.java
  producer/src/main/java/server/producer/domain/service/MapService.java
  producer/src/main/java/server/producer/domain/service/UserService.java
  producer/src/main/java/server/producer/external/controller/naver/NaverLocationController.java
  producer/src/main/resources/application.yaml
  producer/src/test/java/domain/repository/FilterRepositoryTest.java
  producer/src/test/java/domain/repository/HouseRepositoryTest.java
  producer/src/test/java/domain/repository/UserRepositoryTest.java
  producer/src/test/java/domain/service/HouseServiceTest.java
  producer/src/test/java/domain/service/MapServiceTest.java
  producer/src/test/java/domain/service/UserServiceTest.java
Labels: fix

#51 [Fix] #49 controller 에러 분기처리
  .github/workflows/cd-workflow.yml
  common/build.gradle
  common/src/main/java/entity/History.java
  common/src/main/java/entity/House.java
  common/src/main/java/entity/Pin.java
  common/src/main/java/entity/Room.java
  common/src/main/java/entity/Roommate.java
  common/src/main/resources/application.yaml
  consumer/build.gradle
  consumer/src/main/java/server/consumer/processor/TourQueueProcessor.java
  consumer/src/main/java/server/consumer/repository/HistoryRepository.java
  consumer/src/main/resources/application.yaml
  consumer/src/test/java/processor/TourQueueProcessorTest.java
  producer/build.gradle
  producer/src/main/java/server/producer/common/aspect/ApiLoggingAspect.java
  producer/src/main/java/server/producer/common/dto/enums/ErrorCode.java
  producer/src/main/java/server/producer/common/dto/enums/SuccessCode.java
  producer/src/main/java/server/producer/domain/controller/HouseController.java
  producer/src/main/java/server/producer/domain/controller/MapController.java
  producer/src/main/java/server/producer/domain/controller/RoomController.java
  producer/src/main/java/server/producer/domain/controller/UserController.java
  producer/src/main/java/server/producer/domain/dto/request/FilterRequestDto.java
  producer/src/main/java/server/producer/domain/dto/response/HouseDetailsResponseDto.java
  producer/src/main/java/server/producer/domain/repository/FilterRepository.java
  producer/src/main/java/server/producer/domain/repository/HouseRepository.java
  producer/src/main/java/server/producer/domain/repository/PinRepository.java
  producer/src/main/java/server/producer/domain/repository/UserRepository.java
  producer/src/main/java/server/producer/domain/service/HouseService.java
  producer/src/main/java/server/producer/domain/service/MapService.java
  producer/src/main/java/server/producer/domain/service/RoomService.java
  producer/src/main/java/server/producer/domain/service/UserService.java
  producer/src/main/java/server/producer/external/controller/naver/NaverLocationController.java
  producer/src/main/java/server/producer/external/repository/HistoryRepository.java
  producer/src/main/java/server/producer/external/service/redis/QueueService.java
  producer/src/main/java/server/producer/external/service/redis/RedisSender.java
  producer/src/main/resources/application.yaml
  producer/src/test/java/domain/repository/FilterRepositoryTest.java
  producer/src/test/java/domain/repository/HouseRepositoryTest.java
  producer/src/test/java/domain/repository/UserRepositoryTest.java
  producer/src/test/java/domain/service/HouseServiceTest.java
  producer/src/test/java/domain/service/MapServiceTest.java
  producer/src/test/java/domain/service/UserServiceTest.java
Labels: fix

#62 [Fix] #50
  producer/src/main/java/server/producer/domain/controller/HouseController.java
  producer/src/main/java/server/producer/domain/dto/response/PinnedResponseDto.java
  producer/src/main/java/server/producer/domain/service/HouseService.java
Labels: fix
